# Generated by Django 5.0.6 on 2024-06-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_date_sold_record_make_record_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='total_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
