# Generated by Django 5.0.6 on 2024-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_discount_amount_record_payment_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='next_payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
