# Generated by Django 5.0.6 on 2024-06-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_next_payment_due_record_payment_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='CustomerRecord',
        ),
    ]
