# Generated by Django 5.0.6 on 2024-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_record_customerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='customer_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='num_payments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
