# Generated by Django 5.0.6 on 2024-06-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customerrecord_customer_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrecord',
            name='customer_paid',
        ),
        migrations.RemoveField(
            model_name='customerrecord',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='customerrecord',
            name='next_payment_due',
        ),
        migrations.RemoveField(
            model_name='customerrecord',
            name='num_payments',
        ),
        migrations.RemoveField(
            model_name='customerrecord',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='customerrecord',
            name='payment_start_date',
        ),
        migrations.RemoveField(
            model_name='customerrecord',
            name='total_down_payment',
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly')], max_length=20)),
                ('payment_start_date', models.DateField()),
                ('next_payment_due', models.DateField(blank=True, null=True)),
                ('num_payments', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='website.customerrecord')),
            ],
        ),
    ]
