# Generated by Django 5.0.6 on 2024-06-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_customerrecord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='customer_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='next_payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='num_payments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='total_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PaymentSchedule',
        ),
    ]
