# Generated by Django 5.0.6 on 2024-06-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_customerrecord_customer_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payments_made', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Adjusted', 'Adjusted')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='website.customerrecord')),
            ],
        ),
    ]
